# Stage 1: SQL Server
FROM mcr.microsoft.com/mssql/server:2022-latest AS sqlserver

ENV SA_PASSWORD=YourStrong!Passw0rd
ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Developer

# Stage 2: Tools
FROM mcr.microsoft.com/mssql-tools AS tools

# Copy sqlcmd vào container SQL Server
COPY --from=tools /opt/mssql-tools /opt/mssql-tools

# Set PATH để dùng sqlcmd
ENV PATH="$PATH:/opt/mssql-tools/bin"

# Chuyển user về mssql
USER mssql
