[ElectronicStoreDrive]
type = drive
token = {"access_token":"ya29.a0ATi6K2vf0_DlJuhQtdyMeTCxqefAtUpBkW-qsnxiYgcTPCP1HTSSXDzI8PfsLZrgCMO_kNRDdRzQdh8lilggR_yfXDLlLLOrYVyWeOWqHtx9EUcK9K1EA6IzsJQe3RDJ4tlNgx13ZF_CDoCT0elzd8yySR28q57L6A1IF-uJtWzg_QkR2LPLMgUnph7_SfO_JZfYgW4aCgYKAV4SARcSFQHGX2Mi7C6rUNsSIf2qhVJ4ZXL8MQ0206","token_type":"Bearer","refresh_token":"1//0gGP4rywJFvu6CgYIARAAGBASNwF-L9IrAg9GU7KwTqgIn3SLReZYl17Lqpyst1zYT9kI4fWMnRMUb4CNhe_O8RJy6GX_jPxeQWY","expiry":"2025-11-28T18:23:24.0902962+07:00","expires_in":3599}
team_drive = 

